- hosts: all
  become: yes
  vars:
    new_hostname: web-node
    net_interface: eth0
    # ipv6_subnet_full: '2600:3c03:e001:2100::/64'
    number_ipv6: 10000
    start_port: 10000
  pre_tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: '{{ new_hostname }}'
      tags:
        - terraform

    - name: Update apt list
      apt:
        update_cache: yes

  roles:
    - role: merifri.3proxy
      vars:
        proxy_version: "0.9.4"
        proxy_system_user: 3proxy

        proxy_log: "/var/log/3proxy/3proxy.log"

  tasks:
    - name: Setup squid
      ansible.builtin.import_tasks: ./squid-proxies-v6/squid-proxies-v6.yml
      vars:
        install_dir: "{{ ansible_env.HOME }}"
        squid_dir: "{{ install_dir }}/src/squid"
        script_folder: /opt/v6proxies
    
    - name: Block ICMP ipv4/ipv6
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - { name: net.ipv4.icmp_echo_ignore_all, value: 1 }
        - { name: net.ipv6.icmp.echo_ignore_all, value: 1 }
        # - { name: net.core.rmem_max, value: 67108864 }
        # - { name: net.core.wmem_max, value: 67108864 }
        # - { name: net.core.netdev_max_backlog, value: 250000 }
        # - { name: net.core.somaxconn, value: 4096 }
        # - { name: net.ipv4.tcp_syncookies, value: 1 }
        # - { name: net.ipv4.tcp_tw_reuse, value: 1 }
        # - { name: net.ipv4.tcp_tw_recycle, value: 0 }
        # - { name: net.ipv4.tcp_fin_timeout, value: 30 }
        # - { name: net.ipv4.tcp_keepalive_time, value: 1200 }
        # - { name: net.ipv4.ip_local_port_range, value: "10000 65000" }
        # - { name: net.ipv4.tcp_max_syn_backlog, value: 8192 }
        # - { name: net.ipv4.tcp_max_tw_buckets, value: 5000 }
        # - { name: net.ipv4.tcp_fastopen, value: 3 }
        # - { name: net.ipv4.tcp_mem, value: "25600 51200 102400" }
        # - { name: net.ipv4.tcp_rmem, value: "4096 87380 67108864" }
        # - { name: net.ipv4.tcp_wmem, value: "4096 65536 67108864" }
        # - { name: net.ipv4.tcp_mtu_probing, value: 1 }
        # - { name: net.ipv4.tcp_congestion_control, value: "hybla" }
    
    - name: Install netdata
      ansible.builtin.import_tasks: ./netdata/tasks/main.yml
      tags:
        - netdata

  handlers:
    - name: Restart squid
      systemd:
        name: squid
        state: restarted
        daemon_reload: yes

    - name: Restart 3proxy
      systemd:
        name: 3proxy
        state: restarted
        daemon_reload: yes
