---
- name: Generate conf file
  template:
    src: ../templates/netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: u=wrx,g=rx,o=r,+x
  register: generated_conf
  become: true